CREATE TABLE usuario (
       id SERIAL PRIMARY KEY,
       nome VARCHAR(100) NOT NULL,
       email VARCHAR(100) UNIQUE NOT NULL,
       senha TEXT NOT NULL,
       data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
